### ISSUE TITLE
Build errors 

### ISSUE THREAD

**Issue by Montana** [nytimes/gizmo#477]
Even with using and trying to enforce: 

```toml
[[override]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"
```

I'm still getting errors: 
```bash
../gizmo/server/simple_server.go:103:2: undefined: prometheus.InstrumentHandlerWithOpts
../gizmo/server/simple_server.go:123:3: undefined: prometheus.InstrumentHandler
../gizmo/server/simple_server.go:123:46: undefined: prometheus.UninstrumentedHandler
```

Any help would be greatly appreciated!
